/**
 * Generated from VDM-SL specification: TestPO
 *
 * Source: test.vdmsl
 * Generated by: formal-agent-contracts plugin v0.3.0
 */

// ============================================================
// Contract utilities
// ============================================================

class ContractError extends Error {
  constructor(message: string) {
    super(`[Contract Violation] ${message}`);
    this.name = "ContractError";
  }
}

function contractsEnabled(): boolean {
  return typeof process !== "undefined"
    ? process.env.VDM_CONTRACT_CHECK !== "off"
    : true;
}

function assert(condition: boolean, message: string): asserts condition {
  if (!condition) {
    throw new ContractError(message);
  }
}

// ============================================================
// Type definitions
// ============================================================

/** VDM-SL: UserId = nat1 */
type UserId = number;

function isValidUserId(id: number): boolean {
  return Number.isInteger(id) && id >= 1;
}

/** VDM-SL: Email = seq1 of char */
type Email = string;

function isValidEmail(e: string): boolean {
  return e.length > 0;
}

/** VDM-SL Record: User
 *  inv u == u.age <= 150 */
interface User {
  readonly name: string;
  readonly email: Email;
  readonly age: number;
}

/** 不変条件: inv_User */
function invUser(u: User): boolean {
  return (
    u.name.length > 0 && // seq1 of char
    u.email.length > 0 && // Email = seq1 of char
    Number.isInteger(u.age) &&
    u.age >= 0 && // nat
    u.age <= 150 // inv u == u.age <= 150
  );
}

/** ファクトリ: mk_User */
function mkUser(name: string, email: Email, age: number): User {
  const u: User = { name, email, age };
  if (contractsEnabled()) {
    assert(invUser(u), `User invariant violated: ${JSON.stringify(u)}`);
  }
  return u;
}

// ============================================================
// Functions
// ============================================================

/**
 * VDM-SL: findUser
 *
 * findUser: UserId * map UserId to User -> User
 * findUser(uid, users) == users(uid)
 * pre uid in set dom users
 */
function findUser(uid: UserId, users: Map<UserId, User>): User {
  // Pre-condition
  if (contractsEnabled()) {
    assert(isValidUserId(uid), `Type constraint: uid must be nat1, got ${uid}`);
    assert(users.has(uid), `Pre-condition failed: uid ${uid} not in dom users`);
  }

  // Implementation (from VDM-SL: users(uid))
  const result = users.get(uid)!;

  return result;
}

/**
 * VDM-SL: isAdult
 *
 * isAdult: User -> bool
 * isAdult(u) == u.age >= 18
 */
function isAdult(u: User): boolean {
  if (contractsEnabled()) {
    assert(invUser(u), `Type constraint: u must satisfy User invariant`);
  }

  return u.age >= 18;
}

// ============================================================
// State class (operations)
// ============================================================

/**
 * VDM-SL State: UserDB
 *
 * state UserDB of
 *   users : map UserId to User
 *   nextId : UserId
 * inv mk_UserDB(users, nextId) == nextId not in set dom users
 * init s == s = mk_UserDB({|->}, 1)
 */
class UserDB {
  private _users: Map<UserId, User>;
  private _nextId: UserId;

  constructor() {
    // init s == s = mk_UserDB({|->}, 1)
    this._users = new Map();
    this._nextId = 1;
    this._checkInvariant();
  }

  /** 状態不変条件: nextId not in set dom users */
  private _checkInvariant(): void {
    if (!contractsEnabled()) return;
    assert(
      !this._users.has(this._nextId),
      `State invariant violated: nextId ${this._nextId} already in dom users`
    );
  }

  get users(): ReadonlyMap<UserId, User> {
    return this._users;
  }
  get nextId(): UserId {
    return this._nextId;
  }

  /**
   * VDM-SL Operation: RegisterUser
   *
   * RegisterUser: seq1 of char * Email ==> UserId
   * pre email not in set {users(id).email | id in set dom users}
   * post RESULT in set dom users and users(RESULT).name = name
   */
  registerUser(name: string, email: Email): UserId {
    // Pre-condition
    if (contractsEnabled()) {
      assert(name.length > 0, "Pre-condition failed: name must be non-empty (seq1)");
      assert(
        isValidEmail(email),
        "Pre-condition failed: email must be non-empty (seq1)"
      );
      const existingEmails = new Set(
        [...this._users.values()].map((u) => u.email)
      );
      assert(
        !existingEmails.has(email),
        `Pre-condition failed: email '${email}' already registered`
      );
    }

    // Implementation (from VDM-SL body)
    const uid: UserId = this._nextId;
    this._users.set(uid, mkUser(name, email, 0));
    this._nextId = (this._nextId + 1) as UserId;

    // State invariant
    this._checkInvariant();

    // Post-condition
    if (contractsEnabled()) {
      assert(
        this._users.has(uid),
        `Post-condition failed: RESULT ${uid} not in dom users`
      );
      assert(
        this._users.get(uid)!.name === name,
        `Post-condition failed: users(RESULT).name !== name`
      );
    }

    return uid;
  }
}

// ============================================================
// Smoke test
// ============================================================

function main() {
  console.log("=== TestPO: Generated Code Smoke Test ===\n");

  // 1. ファクトリ関数テスト
  const alice = mkUser("Alice", "alice@example.com", 30);
  console.log("✓ mkUser:", alice);

  // 2. 不変条件テスト
  try {
    mkUser("", "bad@example.com", 30); // name が空 → 違反
    console.log("✗ Should have thrown ContractError");
  } catch (e) {
    console.log("✓ Invariant caught:", (e as Error).message);
  }

  try {
    mkUser("Bob", "bob@example.com", 200); // age > 150 → 違反
    console.log("✗ Should have thrown ContractError");
  } catch (e) {
    console.log("✓ Invariant caught:", (e as Error).message);
  }

  // 3. 関数テスト
  const users = new Map<UserId, User>();
  users.set(1, alice);
  const found = findUser(1, users);
  console.log("✓ findUser:", found);
  console.log("✓ isAdult:", isAdult(alice));

  // 4. 事前条件テスト
  try {
    findUser(999, users); // 存在しないキー → 違反
    console.log("✗ Should have thrown ContractError");
  } catch (e) {
    console.log("✓ Pre-condition caught:", (e as Error).message);
  }

  // 5. 操作テスト
  const db = new UserDB();
  console.log("\n--- UserDB Operations ---");
  const id1 = db.registerUser("Alice", "alice@example.com");
  console.log(`✓ RegisterUser: id=${id1}, users.size=${db.users.size}`);
  const id2 = db.registerUser("Bob", "bob@example.com");
  console.log(`✓ RegisterUser: id=${id2}, users.size=${db.users.size}`);

  // 6. 重複メール → 事前条件違反
  try {
    db.registerUser("Charlie", "alice@example.com");
    console.log("✗ Should have thrown ContractError");
  } catch (e) {
    console.log("✓ Pre-condition caught:", (e as Error).message);
  }

  console.log("\n=== All tests passed ===");
}

main();
