"""
Generated from VDM-SL specification: TestPO

Source: test.vdmsl
Generated by: formal-agent-contracts plugin v0.3.0
"""

from __future__ import annotations
import os
from dataclasses import dataclass
from typing import NewType


# ============================================================
# Contract utilities
# ============================================================

class ContractError(AssertionError):
    """契約違反エラー"""
    def __init__(self, message: str) -> None:
        super().__init__(f"[Contract Violation] {message}")


def contracts_enabled() -> bool:
    """契約チェックの有効/無効（環境変数で制御）"""
    return os.environ.get("VDM_CONTRACT_CHECK", "on") != "off"


# ============================================================
# Type definitions
# ============================================================

# VDM-SL: UserId = nat1
UserId = NewType("UserId", int)


def is_valid_user_id(uid: int) -> bool:
    return isinstance(uid, int) and uid >= 1


# VDM-SL: Email = seq1 of char
Email = NewType("Email", str)


def is_valid_email(e: str) -> bool:
    return isinstance(e, str) and len(e) > 0


@dataclass(frozen=True)
class User:
    """
    VDM-SL Record: User

    User :: name  : seq1 of char
            email : Email
            age   : nat
    inv u == u.age <= 150
    """
    name: str
    email: str
    age: int

    def __post_init__(self) -> None:
        if contracts_enabled():
            assert len(self.name) > 0, \
                f"User invariant: name must be non-empty, got '{self.name}'"
            assert len(self.email) > 0, \
                f"User invariant: email must be non-empty, got '{self.email}'"
            assert isinstance(self.age, int) and self.age >= 0, \
                f"User invariant: age must be nat, got {self.age}"
            assert self.age <= 150, \
                f"User invariant: age <= 150, got {self.age}"


# ============================================================
# Functions
# ============================================================

def find_user(uid: UserId, users: dict[UserId, User]) -> User:
    """
    VDM-SL: findUser

    findUser: UserId * map UserId to User -> User
    findUser(uid, users) == users(uid)
    pre uid in set dom users
    """
    if contracts_enabled():
        assert is_valid_user_id(uid), \
            f"Type constraint: uid must be nat1, got {uid}"
        assert uid in users, \
            f"Pre-condition failed: uid {uid} not in dom users"

    return users[uid]


def is_adult(u: User) -> bool:
    """
    VDM-SL: isAdult

    isAdult: User -> bool
    isAdult(u) == u.age >= 18
    """
    return u.age >= 18


# ============================================================
# State class (operations)
# ============================================================

class UserDB:
    """
    VDM-SL State: UserDB

    state UserDB of
      users : map UserId to User
      nextId : UserId
    inv mk_UserDB(users, nextId) == nextId not in set dom users
    init s == s = mk_UserDB({|->}, 1)
    """

    def __init__(self) -> None:
        self._users: dict[UserId, User] = {}
        self._next_id: UserId = UserId(1)
        self._check_invariant()

    def _check_invariant(self) -> None:
        """状態不変条件: nextId not in set dom users"""
        if not contracts_enabled():
            return
        assert self._next_id not in self._users, \
            f"State invariant: nextId {self._next_id} in dom users"

    @property
    def users(self) -> dict[UserId, User]:
        return dict(self._users)

    @property
    def next_id(self) -> UserId:
        return self._next_id

    def register_user(self, name: str, email: str) -> UserId:
        """
        VDM-SL Operation: RegisterUser

        RegisterUser: seq1 of char * Email ==> UserId
        pre email not in set {users(id).email | id in set dom users}
        post RESULT in set dom users and users(RESULT).name = name
        """
        # Pre-condition
        if contracts_enabled():
            assert len(name) > 0, \
                "Pre-condition: name must be non-empty (seq1)"
            assert is_valid_email(email), \
                "Pre-condition: email must be non-empty (seq1)"
            existing_emails = {u.email for u in self._users.values()}
            assert email not in existing_emails, \
                f"Pre-condition: email '{email}' already registered"

        # Implementation
        uid = self._next_id
        self._users[uid] = User(name=name, email=email, age=0)
        self._next_id = UserId(self._next_id + 1)

        # State invariant
        self._check_invariant()

        # Post-condition
        if contracts_enabled():
            assert uid in self._users, \
                f"Post-condition: {uid} not in dom users"
            assert self._users[uid].name == name, \
                "Post-condition: name mismatch"

        return uid


# ============================================================
# Smoke test
# ============================================================

def main() -> None:
    print("=== TestPO: Generated Code Smoke Test ===\n")

    # 1. ファクトリ（dataclass）テスト
    alice = User(name="Alice", email="alice@example.com", age=30)
    print(f"✓ User: {alice}")

    # 2. 不変条件テスト
    try:
        User(name="", email="bad@example.com", age=30)
        print("✗ Should have raised ContractError")
    except AssertionError as e:
        print(f"✓ Invariant caught: {e}")

    try:
        User(name="Bob", email="bob@example.com", age=200)
        print("✗ Should have raised ContractError")
    except AssertionError as e:
        print(f"✓ Invariant caught: {e}")

    # 3. 関数テスト
    users: dict[UserId, User] = {UserId(1): alice}
    found = find_user(UserId(1), users)
    print(f"✓ find_user: {found}")
    print(f"✓ is_adult: {is_adult(alice)}")

    # 4. 事前条件テスト
    try:
        find_user(UserId(999), users)
        print("✗ Should have raised ContractError")
    except AssertionError as e:
        print(f"✓ Pre-condition caught: {e}")

    # 5. 操作テスト
    db = UserDB()
    print("\n--- UserDB Operations ---")
    id1 = db.register_user("Alice", "alice@example.com")
    print(f"✓ register_user: id={id1}, users.size={len(db.users)}")
    id2 = db.register_user("Bob", "bob@example.com")
    print(f"✓ register_user: id={id2}, users.size={len(db.users)}")

    # 6. 重複メール → 事前条件違反
    try:
        db.register_user("Charlie", "alice@example.com")
        print("✗ Should have raised ContractError")
    except AssertionError as e:
        print(f"✓ Pre-condition caught: {e}")

    print("\n=== All tests passed ===")


if __name__ == "__main__":
    main()
