-- ============================================================
-- TaskManager — Database Schema (SQLite 3 dialect)
-- Generated by: formal-agent-contracts / generate-db-schema v2.1.0
-- Source spec:  examples/task-manager/TaskManager.vdmsl
--
-- Dialect notes vs schema.sql (PostgreSQL):
--  * No ENUM -> TEXT + CHECK IN (R3/LT)
--  * WITHOUT ROWID: prevents SQLite's rowid aliasing from auto-assigning
--    an id on INSERT with id=NULL (which would silently bypass the state
--    invariant); with WITHOUT ROWID a NULL id fails NOT NULL as intended
--  * No deferrable constraint triggers -> the cross-row state invariant
--    (forall id < next_id) is delegated to the application layer +
--    contract tests. An immediate trigger WOULD be expressible if all
--    writers committed to updating the counter before inserting
--    (counter-first ordering keeps the invariant true at every statement
--    boundary); we deliberately avoid imposing that ordering obligation
--    on every writer. See D-CROSS-1.
--  * Status transition trigger IS expressible (R12/LT), but INSERT OR
--    REPLACE resolves PK conflicts as DELETE+INSERT and fires no UPDATE
--    trigger — the app layer must use INSERT ... ON CONFLICT DO UPDATE
--    and never REPLACE INTO tasks. See D-TRANS-1.
-- ============================================================

-- Task record (R1) + 'board : map TaskId to Task' (R2)
-- inv TaskBoard: board(id).id = id -> structural via PRIMARY KEY (R9)
CREATE TABLE IF NOT EXISTS tasks (
  id          INTEGER NOT NULL PRIMARY KEY
                CHECK (id >= 1),                       -- TaskId = nat1 (R4) ; D-NUM-1
  title       TEXT NOT NULL
                CHECK (length(title) > 0 AND length(title) <= 100),   -- (R5, R7)
  description TEXT NOT NULL DEFAULT ''
                CHECK (length(description) <= 500),    -- (R5, R7)
  status      TEXT NOT NULL
                CHECK (status IN ('Todo', 'InProgress', 'Done')),     -- (R3)
  priority    TEXT NOT NULL
                CHECK (priority IN ('Low', 'Medium', 'High')),        -- (R3)
  assignee    TEXT
                CHECK (assignee IS NULL OR length(assignee) > 0)      -- (R5, R6)
) WITHOUT ROWID;

-- 'nextId : TaskId' -> singleton state table (R17)
CREATE TABLE IF NOT EXISTS task_manager_state (
  singleton INTEGER PRIMARY KEY DEFAULT 1 CHECK (singleton = 1),
  next_id   INTEGER NOT NULL CHECK (next_id >= 1)     -- inv: nextId >= 1 (R4, R7)
);

-- init s == mk_TaskManagerState({|->}, 1)
INSERT OR IGNORE INTO task_manager_state (singleton, next_id) VALUES (1, 1);

-- pre ChangeStatus: ValidTransition (R12; D-TRANS-1)
CREATE TRIGGER IF NOT EXISTS trg_tasks_status_transition
  BEFORE UPDATE OF status ON tasks
  WHEN OLD.status = 'Done' AND NEW.status <> 'Done'
BEGIN
  SELECT RAISE(ABORT, 'invalid status transition from Done');
END;

-- inv TaskManagerState: forall id in dom board & id < nextId (R13)
--   Delegated to the application layer + contract tests in this dialect.
--   See header note and D-CROSS-1.
