-- ============================================================
-- TaskManager — Database Schema
-- Generated by: formal-agent-contracts / generate-db-schema v2.1.0
-- Source spec:  examples/task-manager/TaskManager.vdmsl
-- Dialect:      PostgreSQL 15+
-- Naming:       snake_case; VDM field 'desc' renamed to 'description'
--               (SQL keyword avoidance; recorded in TRACEABILITY.md)
-- Idempotency:  re-runnable (types/triggers guarded by DO blocks; see
--               vdm-to-sql-mapping.md 出力の作法 #3 — full migration
--               management is out of scope)
-- Rule IDs (Rn) refer to skills/generate-db-schema/references/vdm-to-sql-mapping.md
-- Deviation IDs (D-*) refer to ./DEVIATIONS.md
-- ============================================================

-- Status = <Todo> | <InProgress> | <Done> (R3)
-- ENUM evolution: adding a quote value later = ALTER TYPE ... ADD VALUE;
-- removal requires a column rewrite. See D-ENUM-1.
DO $$ BEGIN
  CREATE TYPE task_status AS ENUM ('Todo', 'InProgress', 'Done');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- Priority = <Low> | <Medium> | <High> (R3)
DO $$ BEGIN
  CREATE TYPE task_priority AS ENUM ('Low', 'Medium', 'High');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- Task record (R1) + state component 'board : map TaskId to Task' (R2)
-- inv TaskBoard: forall id in set dom board & board(id).id = id
--   -> structurally satisfied: id is the primary key (R9)
CREATE TABLE IF NOT EXISTS tasks (
  id          BIGINT PRIMARY KEY,                 -- TaskId = nat1 (R4) ; D-NUM-1
  title       VARCHAR(100) NOT NULL,              -- seq1 of char, inv: len title <= 100 (R5, R7)
  description VARCHAR(500) NOT NULL DEFAULT '',   -- desc : seq of char, inv: len desc <= 500 (R5, R7)
  status      task_status   NOT NULL,             -- (R3)
  priority    task_priority NOT NULL,             -- (R3)
  assignee    TEXT NULL,                          -- [seq1 of char] (R6)

  CONSTRAINT tasks_id_nat1
    CHECK (id >= 1),                              -- nat1 (R4)
  CONSTRAINT tasks_title_nonempty
    CHECK (length(title) > 0),                    -- seq1 of char (R5)
  CONSTRAINT tasks_assignee_nonempty
    CHECK (assignee IS NULL OR length(assignee) > 0)  -- [seq1 of char] (R5, R6)
);

-- Read paths (FilterByStatus / FilterByPriority / GetAssignedTasks) scan by
-- non-key columns; enable these when data volume warrants:
-- CREATE INDEX IF NOT EXISTS idx_tasks_status   ON tasks (status);
-- CREATE INDEX IF NOT EXISTS idx_tasks_priority ON tasks (priority);
-- CREATE INDEX IF NOT EXISTS idx_tasks_assignee ON tasks (assignee) WHERE assignee IS NOT NULL;

-- state component 'nextId : TaskId' -> singleton state table (R17)
-- SEQUENCE/IDENTITY replacement was REJECTED — see D-SEQ-1 for the precise
-- reasoning (rollback advances a sequence with no corresponding spec
-- operation, breaking trace-level correspondence with the explicit body
-- 'nextId := nextId + 1').
CREATE TABLE IF NOT EXISTS task_manager_state (
  singleton BOOLEAN PRIMARY KEY DEFAULT TRUE CHECK (singleton),
  next_id   BIGINT NOT NULL
    CONSTRAINT state_next_id_nat1 CHECK (next_id >= 1)  -- inv: nextId >= 1 (R4, R7)
);
-- NOTE: nothing in DDL prevents DELETE of the singleton row; the app layer
-- must not delete it (consider REVOKE DELETE in production). The STRICT
-- lookup in enforce_task_id_lt_next() turns a missing row into an error
-- rather than a silent pass.

-- init s == mk_TaskManagerState({|->}, 1)
INSERT INTO task_manager_state (singleton, next_id)
VALUES (TRUE, 1)
ON CONFLICT DO NOTHING;

-- ------------------------------------------------------------
-- inv TaskManagerState: forall id in set dom board & id < nextId (R13; D-CROSS-1)
-- Enforced TWO-SIDED as deferred constraint triggers: the invariant reads
-- over both tables, so both mutation paths are guarded.
--   side 1: INSERT/UPDATE of tasks.id      -> trg_tasks_id_lt_next
--   side 2: UPDATE lowering state.next_id  -> trg_state_next_id_gt_tasks
-- Deferral to COMMIT mirrors the VDM 'atomic' block in CreateTask (R15):
-- within the transaction the invariant may be temporarily false.
-- ------------------------------------------------------------
CREATE OR REPLACE FUNCTION enforce_task_id_lt_next() RETURNS trigger AS $$
DECLARE nid BIGINT;
BEGIN
  SELECT next_id INTO STRICT nid FROM task_manager_state WHERE singleton;
  IF NEW.id >= nid THEN
    RAISE EXCEPTION 'state invariant violated: task id % must be < next_id %',
      NEW.id, nid USING ERRCODE = 'check_violation';
  END IF;
  RETURN NEW;
END $$ LANGUAGE plpgsql;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger
                 WHERE tgname = 'trg_tasks_id_lt_next'
                   AND tgrelid = 'tasks'::regclass) THEN
    EXECUTE 'CREATE CONSTRAINT TRIGGER trg_tasks_id_lt_next
      AFTER INSERT OR UPDATE OF id ON tasks
      DEFERRABLE INITIALLY DEFERRED
      FOR EACH ROW EXECUTE FUNCTION enforce_task_id_lt_next()';
  END IF;
END $$;

CREATE OR REPLACE FUNCTION enforce_next_id_gt_all_tasks() RETURNS trigger AS $$
BEGIN
  IF EXISTS (SELECT 1 FROM tasks WHERE id >= NEW.next_id) THEN
    RAISE EXCEPTION 'state invariant violated: next_id % must exceed every task id',
      NEW.next_id USING ERRCODE = 'check_violation';
  END IF;
  RETURN NEW;
END $$ LANGUAGE plpgsql;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger
                 WHERE tgname = 'trg_state_next_id_gt_tasks'
                   AND tgrelid = 'task_manager_state'::regclass) THEN
    -- WHEN guard: normal CreateTask increments never pay this check
    EXECUTE 'CREATE CONSTRAINT TRIGGER trg_state_next_id_gt_tasks
      AFTER UPDATE OF next_id ON task_manager_state
      DEFERRABLE INITIALLY DEFERRED
      FOR EACH ROW WHEN (NEW.next_id < OLD.next_id)
      EXECUTE FUNCTION enforce_next_id_gt_all_tasks()';
  END IF;
END $$;

-- ------------------------------------------------------------
-- pre ChangeStatus: ValidTransition(board(taskId).status, newStatus) (R12; D-TRANS-1)
-- ValidTransition: same -> same is a no-op; any transition OUT of Done is denied.
-- WHEN (IS DISTINCT FROM) fires on actual change regardless of how the UPDATE
-- was produced, and skips the function on unrelated updates.
-- ------------------------------------------------------------
CREATE OR REPLACE FUNCTION enforce_task_status_transition() RETURNS trigger AS $$
BEGIN
  IF OLD.status = 'Done' AND NEW.status <> 'Done' THEN
    RAISE EXCEPTION 'invalid status transition: Done -> %', NEW.status
      USING ERRCODE = 'check_violation';
  END IF;
  RETURN NEW;
END $$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER trg_tasks_status_transition
  BEFORE UPDATE ON tasks
  FOR EACH ROW WHEN (OLD.status IS DISTINCT FROM NEW.status)
  EXECUTE FUNCTION enforce_task_status_transition();

-- ============================================================
-- Operation -> transaction mapping (R15)
--
-- CreateTask   : ONE transaction —
--                  UPDATE task_manager_state
--                    SET next_id = next_id + 1
--                    WHERE singleton
--                    RETURNING next_id - 1 AS new_id;   -- takes the row lock
--                  INSERT INTO tasks (id, ...) VALUES (:new_id, ...);
--                COMMIT (deferred triggers check here).
--                Counter-update-first keeps the invariant true at every
--                statement boundary and serializes numbering at READ
--                COMMITTED without a separate FOR UPDATE. See D-TX-1.
-- ChangeStatus : single UPDATE (trigger enforces the transition rule;
--                existence conjunct of the pre = app layer checks the
--                affected row count = 1).
--                Do NOT bypass via DELETE + re-INSERT; see D-TRANS-1.
-- UpdateTask   : single UPDATE (lengths enforced by DDL; existence = row count).
-- DeleteTask   : single DELETE (existence = row count).
-- GetSummary   : read-only; post-condition (t+i+d = card dom board) holds per
--                statement snapshot; verified by contract tests, not the DB.
-- ============================================================
